name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  IMAGE_NAME: s2i-nodejs-nginx
  QUAY_USER: evanshortiss
  LATEST_VERSION: "14" 

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo "TODO: image testing"
          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test
    strategy:
      matrix:
        versions: ["14", "12", "10"]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build Alpine with NGINX 1.18
        run: docker build . --file alpine.Dockerfile --build-arg NGINX_VERSION="1.18" --build-arg NODE_VERSION=${{ matrix.versions }} --build-arg APK_REPO=http://dl-cdn.alpinelinux.org/alpine/v3.12/main --tag quay.io/$QUAY_USER/$IMAGE_NAME:${{ matrix.versions }}-nginx1.18

      - name: Build Alpine with NGINX 1.16
        run: docker build . --file alpine.Dockerfile --build-arg NGINX_VERSION="1.16" --build-arg NODE_VERSION=${{ matrix.versions }} --build-arg APK_REPO=http://dl-cdn.alpinelinux.org/alpine/v3.10/main --tag quay.io/$QUAY_USER/$IMAGE_NAME:${{ matrix.versions }}-nginx1.16

      - name: Tag "latest" image
        if: ${{ matrix.versions }} == env.LATEST_VERSION
        run: docker tag quay.io/$QUAY_USER/$IMAGE_NAME:${{ matrix.versions }}-nginx1.18 quay.io/$QUAY_USER/$IMAGE_NAME:latest
      
      - name: Log into the quay.io registry
        run: echo "${{ secrets.QUAY_ROBOT_PASS }}" | docker login quay.io -u ${{ secrets.QUAY_ROBOT_NAME }} --password-stdin

      - name: Push images to quay.io
        run: |
          docker push quay.io/$QUAY_USER/$IMAGE_NAME:latest
          docker push quay.io/$QUAY_USER/$IMAGE_NAME:${{ matrix.versions }}-nginx1.18
          docker push quay.io/$QUAY_USER/$IMAGE_NAME:${{ matrix.versions }}-nginx1.16

